"""Initial schema with all core tables

Revision ID: 0acd3e6b9445
Revises: 
Create Date: 2025-11-19 22:47:18.916851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acd3e6b9445'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('settings', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_companies_invite', ['invite_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_invite_token'), ['invite_token'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'regular', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_company', ['company_id'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starting_url', sa.String(), nullable=False),
    sa.Column('tags', sa.Text(), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'active', 'needs_review', 'broken', 'archived', name='workflow_status'), server_default='draft', nullable=False),
    sa.Column('success_rate', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('total_uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_run', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('idx_workflows_company', ['company_id'], unique=False)
        batch_op.create_index('idx_workflows_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_workflows_status', ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('read_by', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='notification_severity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['read_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_company', ['company_id', 'read', 'created_at'], unique=False)

    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), server_default='jpeg', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index('idx_screenshots_hash', ['hash'], unique=False)
        batch_op.create_index('idx_screenshots_workflow', ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshots_hash'), ['hash'], unique=True)

    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_id', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('selectors', sa.Text(), nullable=False),
    sa.Column('element_meta', sa.Text(), nullable=False),
    sa.Column('page_context', sa.Text(), nullable=False),
    sa.Column('action_data', sa.Text(), nullable=True),
    sa.Column('dom_context', sa.Text(), nullable=True),
    sa.Column('field_label', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_edited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('instruction_edited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('healed_selectors', sa.Text(), nullable=True),
    sa.Column('healed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('healing_confidence', sa.Float(), nullable=True),
    sa.Column('healing_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'step_number', name='uq_workflow_step_number')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index('idx_steps_screenshot', ['screenshot_id'], unique=False)
        batch_op.create_index('idx_steps_workflow', ['workflow_id'], unique=False)

    op.create_table('health_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('healing_confidence', sa.Float(), nullable=True),
    sa.Column('deterministic_score', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('candidates_evaluated', sa.Integer(), nullable=True),
    sa.Column('page_state_hash', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_logs', schema=None) as batch_op:
        batch_op.create_index('idx_health_logs_status', ['status'], unique=False)
        batch_op.create_index('idx_health_logs_workflow', ['workflow_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_health_logs_workflow')
        batch_op.drop_index('idx_health_logs_status')

    op.drop_table('health_logs')
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index('idx_steps_workflow')
        batch_op.drop_index('idx_steps_screenshot')

    op.drop_table('steps')
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshots_hash'))
        batch_op.drop_index('idx_screenshots_workflow')
        batch_op.drop_index('idx_screenshots_hash')

    op.drop_table('screenshots')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_company')

    op.drop_table('notifications')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('idx_workflows_status')
        batch_op.drop_index('idx_workflows_created_by')
        batch_op.drop_index('idx_workflows_company')

    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_company')

    op.drop_table('users')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_invite_token'))
        batch_op.drop_index('idx_companies_invite')

    op.drop_table('companies')
    # ### end Alembic commands ###
